development:
  adapter: postgresql
  encoding: unicode
  database: COSI105CachingAssginment
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: COSI105CachingAssginment
  pool: 2

production:
  adapter: postgresql
  encoding: unicode
  database: COSI105CachingAssginment
  pool: 2
  username: your_username
  password: your_password